/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.mathis.stuba.sipproxy;

import javax.swing.JTable;
import javax.swing.JTextArea;

/**
 *
 * @author martinhudec
 */
public class CallMessages extends javax.swing.JPanel {

    /**
     * Creates new form callMessages
     */
    private AppGuiController guicontroller;
    private int id;
    public CallMessages(AppGuiController guicontroller) {
        initComponents();
        
        this.guicontroller = guicontroller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        callsTable = new javax.swing.JTable();
        savetofile = new javax.swing.JButton();

        messageArea.setEditable(false);
        messageArea.setColumns(20);
        messageArea.setRows(5);
        jScrollPane1.setViewportView(messageArea);

        callsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Caller name", "Caller IP / port", "Caller extension", "Callee name", "Callee IP /port", "Callee extension", "Call duration", "Call state"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(callsTable);
        if (callsTable.getColumnModel().getColumnCount() > 0) {
            callsTable.getColumnModel().getColumn(0).setMinWidth(25);
            callsTable.getColumnModel().getColumn(0).setMaxWidth(25);
            callsTable.getColumnModel().getColumn(1).setResizable(false);
            callsTable.getColumnModel().getColumn(2).setResizable(false);
            callsTable.getColumnModel().getColumn(3).setResizable(false);
            callsTable.getColumnModel().getColumn(4).setResizable(false);
            callsTable.getColumnModel().getColumn(5).setResizable(false);
            callsTable.getColumnModel().getColumn(6).setResizable(false);
            callsTable.getColumnModel().getColumn(7).setResizable(false);
            callsTable.getColumnModel().getColumn(8).setResizable(false);
        }

        savetofile.setText("save to textFile");
        savetofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savetofileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 809, Short.MAX_VALUE)
                .addComponent(savetofile))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savetofile))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void savetofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savetofileActionPerformed
    guicontroller.saveToFile(messageArea);
    }//GEN-LAST:event_savetofileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable callsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JButton savetofile;
    // End of variables declaration//GEN-END:variables

    public JTable getCallsTable() {
        return callsTable;
    }

    public JTextArea getMessageArea() {
        return messageArea;
    }

}
